paths:
    config_dir: "/home/hess/projects/discriminator-guidance/configs"
    output_dir: "/p/tmp/hess/scratch/discriminator-guidance/results/experiments/"
    output_fname: "vorticity_conditional.nc"
    discriminator_config_fname: null
    diffusion_config_fname: "diffusion_cond_vorticity_config.yaml"

models:
    discriminator_model_id: null
    diffusion_model_id:  "rdwrcqmr" 

experiment:
    forecast: false
    noise_shape: [1, 1, 256, 256]
    variable_name: "vorticity"
    use_conditioning: true
    use_past_state: true
    use_past_2_state: false
    num_diffusion_steps: 50
    num_rollout_steps: 4000
    num_samples: 1
    guidance_weight: 0
    s_noise: 1.001
    s_churn: 55
    noise_delta: 0.0
    epsilon_scaling: 1.0
    t_min: 0.0
    to_physical: true
    to_xarray: true
    show_progress: false
    show_rollout_progress: true
    flush_output_dir: null